# Site settings
title: Bryan Colosky
email: hello@bryancolosky.com
first_name: Bryan
last_name: Colosky

twitter_username:   bryancolosky
github_username:    bryancolosky
unsplash_username:  bryancolosky
gravatar_id:        823811c7dedcd8bf752cfe686563f439



description: >
  Bryan Colosky is a multidisciplinary designer in Brooklyn, New York.

port: 4000
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://bryancolosky.com" # the base hostname & protocol for your site

# Permalink setiings
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jemoji

# Web Fonts
adobe_id:       bmd3xqv
fontawesome_id:

# Collection Settings
collections:
  projects:
    output: true
    permalink: /:collection/:name/

  photographs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: projects
  - scope:
      path: ""
      type: "photographs"
    values:
      layout: photographs

# Excludes
exclude: [package.json, package-lock.json, bower.json, gulpfile.js, node_modules, bower_components, gulp, /**/styles, /**/scripts, .bowerrc, .sass-cache, .DS_Store, .gitignore, .editorconfig, .jshintrc, /*.txt, /*.ai, /*.pdf, /*.indd, /*.idlk, /*.psd, /*.yml, /*~orig*]
