# Site settings
title: Bryan Colosky
email: hello@bryancolosky.com
first_name: Bryan
last_name: Colosky

twitter_username:   bryancolosky
github_username:    bryancolosky
unsplash_username:  bryancolosky
gravatar_id:        823811c7dedcd8bf752cfe686563f439
gravatar_userimage: 019959a534bd8ba1336491506f7fdb40
google_analytics:   UA-77290484-2

description: >
  Bryan Colosky is a multidisciplinary designer in Brooklyn, New York.

port: 4000
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bryancolosky.com" # the base hostname & protocol for your site

# Permalink setiings
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jemoji

# Web Fonts
adobe_id:       bmd3xqv
fontawesome_id:

# Collection Settings
collections:
  projects:
    output: true
    permalink: /:collection/:name/

  photographs:
    output: true
    permalink: /:collection/:path/

  docs:
    output: true
    permalink: /:collection/:path/

  patterns:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: "_projects"
    values:
      layout: feed
      type: project
  -
    scope:
      path: "_photographs"
      type: "photographs"
    values:
      layout: feed
      type: photograph
  -
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
  -
    scope:
      path: "_docs/foundations"
    values:
      layout: doc
      type: foundation
  -
    scope:
      path: "_docs/guidelines"
    values:
      layout: doc
      type: guideline
  -
    scope:
      path: "_docs/components"
    values:
      layout: doc
      type: component
  -
    scope:
      path: "_patterns"
    values:
      layout: pattern.webpack
      type: pattern
      maturity: planned
      title: Not Assigned
      styles: Not Assigned

exclude:
  - LICENSE
  - Gemfile
  - node_modules
  - bower_components
  - favicons
  - html
  - images
  - js
  - scss
  - svg
  - vendor
  - Gemfile.lock
  - gulpfile.js
  - postcss.config.js
  - webpack.config.js
  - bower.json
  - package.json
  - package-lock.json
  - yarn-error.log
  - yarn.lock
  - README.md
  - .bowerrc
  - .editorconfig
  - .DS_Store
  - .gitignore
  - .jekyll-metadata
  - .jshintrc
  - .sass-cache
  - /*.ai
  - /*.indd
  - /*.idlk
  - /*.log
  - /*.pdf
  - /*.psd
  - /*.rp
  - /*.terminal
  - /*src*
  - /*orig*
